import { APP_HOME_URL, renderHeader, renderFooter, wrapHtmlDoc } from './base.js';

export function renderTestTemplate(data = {}) {
  const recipient = data.recipient || data.to || 'Administrator';
  const timestamp = new Date().toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' });

  const bodyContent = `
    ${renderHeader('SMTP Diagnostic Test')}
    <tr>
      <td style="padding: 30px 24px; text-align: center;">
        <div style="font-size: 40px; margin-bottom: 12px;">✅</div>
        <div style="font-size: 20px; font-weight: 800; color: #0f172a; margin-bottom: 6px;">
          SMTP Connection Successful!
        </div>
        <p style="font-size: 14px; color: #475569; line-height: 1.6; margin: 0 0 24px 0;">
          Your project email delivery gateway is online, verified, and operational.
        </p>

        <table width="100%" border="0" cellpadding="0" cellspacing="0" style="background-color: #f8fafc; border: 1px solid #e2e8f0; border-radius: 12px; margin-bottom: 24px;">
          <tr>
            <td style="padding: 16px 20px; text-align: left;">
              <table width="100%" border="0" cellpadding="0" cellspacing="0" style="font-size: 12px; font-family: monospace;">
                <tr>
                  <td style="padding: 4px 0; color: #64748b;">Recipient:</td>
                  <td align="right" style="padding: 4px 0; color: #0f172a; font-weight: 700;">${recipient}</td>
                </tr>
                <tr>
                  <td style="padding: 4px 0; color: #64748b;">Status:</td>
                  <td align="right" style="padding: 4px 0; color: #16a34a; font-weight: 700;">200 OK &bull; Active</td>
                </tr>
                <tr>
                  <td style="padding: 4px 0; color: #64748b;">Server Time:</td>
                  <td align="right" style="padding: 4px 0; color: #0f172a;">${timestamp} IST</td>
                </tr>
              </table>
            </td>
          </tr>
        </table>

        <table width="100%" border="0" cellpadding="0" cellspacing="0">
          <tr>
            <td align="center">
              <a href="${APP_HOME_URL}" target="_blank" style="display: inline-block; background-color: #0057BB; background: linear-gradient(135deg, #0057BB 0%, #00479e 100%); color: #ffffff !important; text-decoration: none; padding: 12px 28px; border-radius: 10px; font-size: 13px; font-weight: 700;">
                Return to HisabKhata &rarr;
              </a>
            </td>
          </tr>
        </table>
      </td>
    </tr>
    ${renderFooter({
      badgeText: 'SYSTEM HEALTH PASS',
      badgeBg: '#ecfdf5',
      badgeBorder: '#a7f3d0',
      badgeColor: '#065f46',
      disclaimer: 'This is an automated system diagnostic email generated by HisabKhata backend.'
    })}`;

  return wrapHtmlDoc(bodyContent, 'HisabKhata SMTP Diagnostic Test');
}
