name = "hisabkhata-backend"
main = "src/index.js"
compatibility_date = "2024-09-01"
compatibility_flags = [ "nodejs_compat" ]
workers_dev = true

routes = [
	{ pattern = "backend.hisabkhata.sumanonline.com", custom_domain = true }
]

[[r2_buckets]]
binding = "MY_BUCKET"
bucket_name = "hisabkhata"

[triggers]
crons = [ "0 4 * * *", "0 4 * * 1" ]

[vars]
PUBLIC_CDN_URL = "https://cdn.backend.hisabkhata.sumanonline.com"
ENVIRONMENT = "production"
FIREBASE_DB_URL = "https://hisabkhata-sumanonline-default-rtdb.asia-southeast1.firebasedatabase.app"
SMTP_HOST = "smtp.gmail.com"
SMTP_PORT = "465"
SMTP_SECURE = "true"
SMTP_FROM_NAME = "HisabKhata PRO"
SMTP_FROM_EMAIL = "hisabkhata@sumanonline.com"
