name = "hisabkhata-backend"
main = "src/index.js"
compatibility_date = "2024-09-01"
compatibility_flags = [ "nodejs_compat" ]
workers_dev = true

routes = [
	{ pattern = "backend.hisabkhata.sumanonline.com", custom_domain = true }
]

# Cloudflare R2 Bucket Binding
[[r2_buckets]]
binding = "MY_BUCKET"
bucket_name = "hisabkhata"

[vars]
PUBLIC_CDN_URL = "https://cdn.backend.hisabkhata.sumanonline.com"
ENVIRONMENT = "production"

# Custom SMTP Configuration (Set values here or as Secrets in Cloudflare Dashboard)
SMTP_HOST = "smtp.gmail.com"
SMTP_PORT = "465"
SMTP_SECURE = "true"
SMTP_USER = ""
SMTP_PASS = ""
SMTP_FROM_NAME = "HisabKhata PRO"
SMTP_FROM_EMAIL = "noreply@sumanonline.com"

