
const BRAND_LOGO_URL = 'https://hisabkhata.sumanonline.com/icons/icon-192x192.png';
const APP_HOME_URL = 'https://hisabkhata.sumanonline.com/';
const SUMAN_ONLINE_URL = 'https://sumanonline.com';

function renderHeader(subtitle = 'A SumanOnline Project') {
  return `
    <tr>
      <td align="center" bgcolor="#0057BB" style="background-color: #0057BB; background: linear-gradient(135deg, #0057BB 0%, #003a80 100%); padding: 30px 24px; text-align: center;">
        <table border="0" cellpadding="0" cellspacing="0" align="center" style="margin: 0 auto;">
          <tr>
            <td valign="middle" style="padding-right: 10px;">
              <img src="${BRAND_LOGO_URL}" width="36" height="36" alt="HisabKhata" style="display: block; width: 36px; height: 36px; border-radius: 9px; vertical-align: middle; border: 0;" />
            </td>
            <td valign="middle" style="font-size: 26px; font-weight: 800; color: #ffffff; letter-spacing: -0.5px; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Arial, sans-serif; line-height: 28px;">
              HisabKhata
            </td>
            <td valign="middle" style="padding-left: 8px;">
              <table border="0" cellpadding="0" cellspacing="0">
                <tr>
                  <td bgcolor="#ef4444" style="background-color: #ef4444; color: #ffffff; font-size: 11px; font-weight: 800; padding: 3px 7px; border-radius: 4px; text-transform: uppercase; letter-spacing: 0.5px; line-height: 14px; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Arial, sans-serif;">
                    PRO
                  </td>
                </tr>
              </table>
            </td>
          </tr>
        </table>
        <div style="font-size: 12px; color: #bfdbfe; font-weight: 600; margin-top: 6px; letter-spacing: 0.3px; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Arial, sans-serif;">
          ${subtitle}
        </div>
      </td>
    </tr>`;
}

function renderFooter({
  badgeText = 'VERIFIED DIGITAL STATEMENT',
  badgeBg = '#ecfdf5',
  badgeBorder = '#a7f3d0',
  badgeColor = '#065f46',
  disclaimer = 'This is an official automated notification generated by HisabKhata for real-time digital ledger accounting.'
} = {}) {
  return `
    <tr>
      <td align="center" bgcolor="#f8fafc" style="background-color: #f8fafc; border-top: 1px solid #e2e8f0; padding: 24px 20px; text-align: center;">
        <table border="0" cellpadding="0" cellspacing="0" align="center" style="margin: 0 auto 10px auto;">
          <tr>
            <td bgcolor="${badgeBg}" style="background-color: ${badgeBg}; border: 1px solid ${badgeBorder}; color: ${badgeColor}; font-weight: 700; font-size: 10px; padding: 4px 12px; border-radius: 9999px; letter-spacing: 0.5px; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Arial, sans-serif;">
              &#10003; ${badgeText}
            </td>
          </tr>
        </table>
        <div style="color: #475569; font-size: 11px; max-width: 440px; margin: 0 auto; line-height: 1.5; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Arial, sans-serif;">
          ${disclaimer}
        </div>
        <div style="color: #94a3b8; font-size: 10px; margin-top: 6px; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Arial, sans-serif;">
          For any questions regarding your account or entries, please contact your merchant directly.
        </div>
        <div style="margin-top: 12px; padding-top: 12px; border-top: 1px solid #f1f5f9; font-size: 11px; color: #64748b; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Arial, sans-serif;">
          &copy; <a href="${APP_HOME_URL}" target="_blank" style="color: #0057BB; font-weight: 700; text-decoration: none;">HisabKhata</a> &bull; A <a href="${SUMAN_ONLINE_URL}" target="_blank" style="color: #0057BB; font-weight: 700; text-decoration: none;">SumanOnline</a> Project
        </div>
      </td>
    </tr>`;
}

function wrapHtmlDoc(contentHtml, title = 'HisabKhata Notification') {
  return `<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${title}</title>
</head>
<body style="margin: 0; padding: 0; background-color: #f1f5f9; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; color: #1e293b; -webkit-font-smoothing: antialiased;">
  <table width="100%" border="0" cellpadding="0" cellspacing="0" style="background-color: #f1f5f9; padding: 24px 12px; margin: 0;">
    <tr>
      <td align="center" valign="top">
        <table width="100%" border="0" cellpadding="0" cellspacing="0" style="max-width: 560px; background-color: #ffffff; border-radius: 16px; overflow: hidden; border: 1px solid #e2e8f0; box-shadow: 0 4px 20px rgba(0,0,0,0.06);">
          ${contentHtml}
        </table>
      </td>
    </tr>
  </table>
</body>
</html>`.trim();
}

export function renderTransactionTemplate(data) {
  const isGave = data.txType === 'Payment Requested' || data.txType === 'GAVE' || data.txType === 'credit' || (data.amount != null && Number(data.amount) < 0);
  const absAmount = data.amount != null ? Math.abs(Number(data.amount)).toLocaleString('en-IN') : '0';
  const absBalance = data.balance != null ? Math.abs(Number(data.balance)).toLocaleString('en-IN') : absAmount;
  const isBalanceDebit = data.balance != null ? Number(data.balance) < 0 : isGave;
  const merchant = data.merchantName || 'HisabKhata Merchant';
  const customer = data.customerName || 'Valued Customer';
  const dateStr = new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' });
  const timeStr = new Date().toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit', hour12: true });
  const verifyUrl = data.actionUrl || APP_HOME_URL;

  const formattedDesc = data.description 
    ? String(data.description).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/\n/g, '<br/>') 
    : '';

  const bodyContent = `
    ${renderHeader('Digital Ledger Advisory')}
    <tr>
      <td style="padding: 28px 24px;">
        <div style="font-size: 16px; font-weight: 700; color: #0f172a; margin-bottom: 8px;">
          Hello ${customer},
        </div>
        
        <p style="font-size: 14px; color: #475569; line-height: 1.6; margin: 0 0 20px 0;">
          ${data.customMessage || (isGave 
              ? `A new debit entry has been recorded by <strong>${merchant}</strong>.` 
              : `Your payment was successfully received and credited by <strong>${merchant}</strong>.`)}
        </p>

        
        <table width="100%" border="0" cellpadding="0" cellspacing="0" style="background-color: #f8fafc; border: 1px solid #e2e8f0; border-radius: 12px; margin-bottom: 22px;">
          <tr>
            <td align="center" style="padding: 22px 16px;">
              <div style="font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.6px; color: #64748b; margin-bottom: 4px;">
                ${isGave ? 'AMOUNT DUE (GAVE / DEBIT)' : 'PAYMENT RECEIVED (GOT / CREDIT)'}
              </div>
              <div style="font-size: 34px; font-weight: 900; color: ${isGave ? '#dc2626' : '#16a34a'}; margin: 0; letter-spacing: -1px; line-height: 1.2;">
                &#8377;${absAmount}
              </div>
              <div style="margin-top: 8px;">
                <table border="0" cellpadding="0" cellspacing="0" align="center">
                  <tr>
                    <td bgcolor="${isGave ? '#fee2e2' : '#dcfce7'}" style="background-color: ${isGave ? '#fee2e2' : '#dcfce7'}; color: ${isGave ? '#991b1b' : '#166534'}; font-size: 11px; font-weight: 700; padding: 4px 14px; border-radius: 9999px;">
                      ${isGave ? 'Debit Recorded' : 'Credit Settled / Received'}
                    </td>
                  </tr>
                </table>
              </div>
            </td>
          </tr>
        </table>

        
        <table width="100%" border="0" cellpadding="0" cellspacing="0" style="margin-bottom: 20px; font-size: 13px;">
          <tr>
            <td style="padding: 10px 0; border-bottom: 1px solid #f1f5f9; color: #64748b; font-weight: 600;">
              Current Net Balance:
            </td>
            <td align="right" style="padding: 10px 0; border-bottom: 1px solid #f1f5f9; color: #0f172a; font-weight: 700;">
              &#8377;${absBalance} ${isBalanceDebit ? '(Dr / Due)' : '(Cr / Advance)'}
            </td>
          </tr>
          <tr>
            <td style="padding: 10px 0; border-bottom: 1px solid #f1f5f9; color: #64748b; font-weight: 600;">
              Merchant Name:
            </td>
            <td align="right" style="padding: 10px 0; border-bottom: 1px solid #f1f5f9; color: #0f172a; font-weight: 700;">
              ${merchant}
            </td>
          </tr>
          ${data.merchantPhone ? `
          <tr>
            <td style="padding: 10px 0; border-bottom: 1px solid #f1f5f9; color: #64748b; font-weight: 600;">
              Merchant Contact:
            </td>
            <td align="right" style="padding: 10px 0; border-bottom: 1px solid #f1f5f9; color: #0f172a; font-weight: 700;">
              ${data.merchantPhone}
            </td>
          </tr>` : ''}
          <tr>
            <td style="padding: 10px 0; border-bottom: 1px solid #f1f5f9; color: #64748b; font-weight: 600;">
              Date &amp; Time:
            </td>
            <td align="right" style="padding: 10px 0; border-bottom: 1px solid #f1f5f9; color: #0f172a; font-weight: 700;">
              ${dateStr}, ${timeStr}
            </td>
          </tr>
        </table>

        ${formattedDesc ? `
        <div style="margin-bottom: 20px;">
          <div style="font-size: 11px; font-weight: 700; text-transform: uppercase; color: #64748b; margin-bottom: 6px; letter-spacing: 0.5px;">
            Transaction Remarks &amp; Details:
          </div>
          <table width="100%" border="0" cellpadding="0" cellspacing="0">
            <tr>
              <td style="background-color: #f8fafc; border-left: 4px solid #0057BB; padding: 12px 16px; border-radius: 0 8px 8px 0; font-size: 13px; color: #334155; line-height: 1.6;">
                ${formattedDesc}
              </td>
            </tr>
          </table>
        </div>` : ''}

        
        <table width="100%" border="0" cellpadding="0" cellspacing="0" style="margin: 28px 0 12px 0;">
          <tr>
            <td align="center">
              <a href="${verifyUrl}" target="_blank" style="display: inline-block; background-color: #0057BB; background: linear-gradient(135deg, #0057BB 0%, #00479e 100%); color: #ffffff !important; text-decoration: none; padding: 14px 32px; border-radius: 12px; font-size: 14px; font-weight: 700; letter-spacing: 0.3px; box-shadow: 0 4px 14px rgba(0, 87, 187, 0.3);">
                Verify Transaction &rarr;
              </a>
              <div style="font-size: 11px; color: #94a3b8; margin-top: 8px;">
                Click to view verified ledger entry &amp; download PDF statement
              </div>
            </td>
          </tr>
        </table>
      </td>
    </tr>
    ${renderFooter()}`;

  return wrapHtmlDoc(bodyContent, `HisabKhata Transaction Statement - ₹${absAmount}`);
}

export function renderWelcomeTemplate(data) {
  const userName = data.customerName || data.toName || data.name || 'Merchant';
  const actionUrl = data.actionUrl || `${APP_HOME_URL}login`;

  const bodyContent = `
    ${renderHeader('Smart Digital Ledger Platform')}
    <tr>
      <td style="padding: 32px 24px;">
        <div style="text-align: center; margin-bottom: 24px;">
          <div style="display: inline-block; font-size: 38px; margin-bottom: 8px;">🎉</div>
          <div style="font-size: 22px; font-weight: 800; color: #0f172a; letter-spacing: -0.5px;">
            Welcome to HisabKhata!
          </div>
          <div style="font-size: 14px; color: #64748b; margin-top: 4px;">
            Your modern financial ledger &amp; credit accounting companion
          </div>
        </div>

        <p style="font-size: 14px; color: #334155; line-height: 1.6; margin: 0 0 20px 0;">
          Hello <strong>${userName}</strong>, welcome aboard! We are thrilled to empower your business with instant credit tracking, customer online payments, and automated financial statements.
        </p>

        
        <table width="100%" border="0" cellpadding="0" cellspacing="0" style="background-color: #f8fafc; border: 1px solid #e2e8f0; border-radius: 14px; margin-bottom: 24px; padding: 16px;">
          <tr>
            <td style="padding: 10px 8px; vertical-align: top;" width="36">
              <span style="font-size: 20px;">📒</span>
            </td>
            <td style="padding: 10px 8px;">
              <div style="font-size: 13px; font-weight: 700; color: #0f172a;">Real-Time Credit &amp; Debit Tracking</div>
              <div style="font-size: 12px; color: #64748b; line-height: 1.5; margin-top: 2px;">Record Got (Credit) &amp; Gave (Debit) entries with instant calculation of balances.</div>
            </td>
          </tr>
          <tr>
            <td style="padding: 10px 8px; vertical-align: top; border-top: 1px solid #edf2f7;" width="36">
              <span style="font-size: 20px;">💳</span>
            </td>
            <td style="padding: 10px 8px; border-top: 1px solid #edf2f7;">
              <div style="font-size: 13px; font-weight: 700; color: #0f172a;">Customer Online UPI Collection</div>
              <div style="font-size: 12px; color: #64748b; line-height: 1.5; margin-top: 2px;">Share live ledger links allowing customers to pay directly via UPI and upload UTR proof.</div>
            </td>
          </tr>
          <tr>
            <td style="padding: 10px 8px; vertical-align: top; border-top: 1px solid #edf2f7;" width="36">
              <span style="font-size: 20px;">📑</span>
            </td>
            <td style="padding: 10px 8px; border-top: 1px solid #edf2f7;">
              <div style="font-size: 13px; font-weight: 700; color: #0f172a;">Professional PDF Reports &amp; Reminders</div>
              <div style="font-size: 12px; color: #64748b; line-height: 1.5; margin-top: 2px;">Download itemized GST/audit-ready statements and send friendly payment reminders in 1-click.</div>
            </td>
          </tr>
          <tr>
            <td style="padding: 10px 8px; vertical-align: top; border-top: 1px solid #edf2f7;" width="36">
              <span style="font-size: 20px;">🛡️</span>
            </td>
            <td style="padding: 10px 8px; border-top: 1px solid #edf2f7;">
              <div style="font-size: 13px; font-weight: 700; color: #0f172a;">Cloud-Synced &amp; 100% Secure</div>
              <div style="font-size: 12px; color: #64748b; line-height: 1.5; margin-top: 2px;">Your transactions and party records are safely backed up with encrypted cloud storage.</div>
            </td>
          </tr>
        </table>

        
        <table width="100%" border="0" cellpadding="0" cellspacing="0" style="margin: 28px 0 16px 0;">
          <tr>
            <td align="center">
              <a href="${actionUrl}" target="_blank" style="display: inline-block; background-color: #0057BB; background: linear-gradient(135deg, #0057BB 0%, #00479e 100%); color: #ffffff !important; text-decoration: none; padding: 14px 36px; border-radius: 12px; font-size: 15px; font-weight: 700; letter-spacing: 0.3px; box-shadow: 0 4px 14px rgba(0, 87, 187, 0.3);">
                Go to Your Dashboard &rarr;
              </a>
              <div style="font-size: 12px; color: #94a3b8; margin-top: 10px;">
                Start adding customers and recording daily transactions
              </div>
            </td>
          </tr>
        </table>
      </td>
    </tr>
    ${renderFooter({
      badgeText: 'VERIFIED ONBOARDING',
      badgeBg: '#eff6ff',
      badgeBorder: '#bfdbfe',
      badgeColor: '#1e40af',
      disclaimer: 'Welcome to HisabKhata by SumanOnline. If you did not create this account, please ignore this email.'
    })}`;

  return wrapHtmlDoc(bodyContent, 'Welcome to HisabKhata - Smart Digital Ledger');
}

export function renderCustomerAddedTemplate(data) {
  const customer = data.customerName || data.toName || 'Valued Customer';
  const merchant = data.merchantName || 'Your Merchant';
  const actionUrl = data.actionUrl || APP_HOME_URL;

  const bodyContent = `
    ${renderHeader('Digital Account Advisory')}
    <tr>
      <td style="padding: 28px 24px;">
        <div style="font-size: 16px; font-weight: 700; color: #0f172a; margin-bottom: 8px;">
          Hello ${customer},
        </div>
        
        <p style="font-size: 14px; color: #334155; line-height: 1.6; margin: 0 0 20px 0;">
          <strong>${merchant}</strong> has opened a verified digital ledger for you on <strong>HisabKhata</strong> to give you transparent, 24/7 access to your transaction records, bills, and balance settlements.
        </p>

        
        <table width="100%" border="0" cellpadding="0" cellspacing="0" style="background-color: #f8fafc; border: 1px solid #e2e8f0; border-radius: 12px; margin-bottom: 22px;">
          <tr>
            <td style="padding: 18px 20px;">
              <table width="100%" border="0" cellpadding="0" cellspacing="0" style="font-size: 13px;">
                <tr>
                  <td style="padding: 6px 0; color: #64748b; font-weight: 600;">Merchant / Store:</td>
                  <td align="right" style="padding: 6px 0; color: #0f172a; font-weight: 700;">${merchant}</td>
                </tr>
                ${data.merchantPhone ? `
                <tr>
                  <td style="padding: 6px 0; color: #64748b; font-weight: 600;">Contact Phone:</td>
                  <td align="right" style="padding: 6px 0; color: #0f172a; font-weight: 700;">${data.merchantPhone}</td>
                </tr>` : ''}
                <tr>
                  <td style="padding: 6px 0; color: #64748b; font-weight: 600;">Ledger Status:</td>
                  <td align="right" style="padding: 6px 0; color: #16a34a; font-weight: 700;">&#10003; Active &amp; Verified</td>
                </tr>
              </table>
            </td>
          </tr>
        </table>

        
        <div style="background-color: #f0fdf4; border-left: 4px solid #22c55e; padding: 14px 16px; border-radius: 0 8px 8px 0; margin-bottom: 24px; font-size: 13px; color: #166534; line-height: 1.5;">
          <strong>No app installation needed!</strong> You can click the link below at any time to inspect your live balance, download PDF statements, or make UPI payments directly.
        </div>

        
        <table width="100%" border="0" cellpadding="0" cellspacing="0" style="margin: 28px 0 12px 0;">
          <tr>
            <td align="center">
              <a href="${actionUrl}" target="_blank" style="display: inline-block; background-color: #0057BB; background: linear-gradient(135deg, #0057BB 0%, #00479e 100%); color: #ffffff !important; text-decoration: none; padding: 14px 34px; border-radius: 12px; font-size: 14px; font-weight: 700; letter-spacing: 0.3px; box-shadow: 0 4px 14px rgba(0, 87, 187, 0.3);">
                View Your Live Ledger &rarr;
              </a>
              <div style="font-size: 11px; color: #94a3b8; margin-top: 8px;">
                Secure link to view your personal transaction statement
              </div>
            </td>
          </tr>
        </table>
      </td>
    </tr>
    ${renderFooter()}`;

  return wrapHtmlDoc(bodyContent, `New HisabKhata Ledger - ${merchant}`);
}

export function renderPaymentVerificationTemplate(data) {
  const customer = data.customerName || 'Customer';
  const merchant = data.merchantName || 'Merchant';
  const amount = data.amount != null ? Math.abs(Number(data.amount)).toLocaleString('en-IN') : '0';
  const txRef = data.transactionId || data.utr || 'Not Provided';
  const actionUrl = data.actionUrl || `${APP_HOME_URL}admin`;
  const dateStr = new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' });
  const timeStr = new Date().toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit', hour12: true });

  const bodyContent = `
    ${renderHeader('Online Payment Alert')}
    <tr>
      <td style="padding: 28px 24px;">
        <div style="font-size: 16px; font-weight: 700; color: #0f172a; margin-bottom: 8px;">
          Hello ${merchant},
        </div>
        
        <p style="font-size: 14px; color: #334155; line-height: 1.6; margin: 0 0 20px 0;">
          <strong>${customer}</strong> has submitted an online payment proof for verification and ledger settlement.
        </p>

        
        <table width="100%" border="0" cellpadding="0" cellspacing="0" style="background-color: #fffbeb; border: 1px solid #fef3c7; border-radius: 12px; margin-bottom: 22px;">
          <tr>
            <td align="center" style="padding: 22px 16px;">
              <div style="font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.6px; color: #b45309; margin-bottom: 4px;">
                SUBMITTED ONLINE PAYMENT
              </div>
              <div style="font-size: 34px; font-weight: 900; color: #0057BB; margin: 0; letter-spacing: -1px; line-height: 1.2;">
                &#8377;${amount}
              </div>
              <div style="margin-top: 8px;">
                <table border="0" cellpadding="0" cellspacing="0" align="center">
                  <tr>
                    <td bgcolor="#fef3c7" style="background-color: #fef3c7; color: #92400e; font-size: 11px; font-weight: 700; padding: 4px 14px; border-radius: 9999px; border: 1px solid #fde68a;">
                      Pending Merchant Approval
                    </td>
                  </tr>
                </table>
              </div>
            </td>
          </tr>
        </table>

        
        <table width="100%" border="0" cellpadding="0" cellspacing="0" style="margin-bottom: 20px; font-size: 13px;">
          <tr>
            <td style="padding: 10px 0; border-bottom: 1px solid #f1f5f9; color: #64748b; font-weight: 600;">Customer Name:</td>
            <td align="right" style="padding: 10px 0; border-bottom: 1px solid #f1f5f9; color: #0f172a; font-weight: 700;">${customer}</td>
          </tr>
          <tr>
            <td style="padding: 10px 0; border-bottom: 1px solid #f1f5f9; color: #64748b; font-weight: 600;">Transaction Ref / UTR:</td>
            <td align="right" style="padding: 10px 0; border-bottom: 1px solid #f1f5f9; color: #0057BB; font-family: monospace; font-weight: 700;">${txRef}</td>
          </tr>
          <tr>
            <td style="padding: 10px 0; border-bottom: 1px solid #f1f5f9; color: #64748b; font-weight: 600;">Submitted Time:</td>
            <td align="right" style="padding: 10px 0; border-bottom: 1px solid #f1f5f9; color: #0f172a; font-weight: 700;">${dateStr}, ${timeStr}</td>
          </tr>
        </table>

        
        <div style="background-color: #f8fafc; border-left: 4px solid #f59e0b; padding: 12px 16px; border-radius: 0 8px 8px 0; margin-bottom: 24px; font-size: 12px; color: #475569; line-height: 1.5;">
          <strong>Action Required:</strong> Verify the UTR / Ref in your bank account or UPI app, then click below to approve and automatically credit the customer's ledger.
        </div>

        
        <table width="100%" border="0" cellpadding="0" cellspacing="0" style="margin: 28px 0 12px 0;">
          <tr>
            <td align="center">
              <a href="${actionUrl}" target="_blank" style="display: inline-block; background-color: #0057BB; background: linear-gradient(135deg, #0057BB 0%, #00479e 100%); color: #ffffff !important; text-decoration: none; padding: 14px 34px; border-radius: 12px; font-size: 14px; font-weight: 700; letter-spacing: 0.3px; box-shadow: 0 4px 14px rgba(0, 87, 187, 0.3);">
                Review &amp; Approve Payment &rarr;
              </a>
            </td>
          </tr>
        </table>
      </td>
    </tr>
    ${renderFooter({
      badgeText: 'PAYMENT VERIFICATION REQUEST',
      badgeBg: '#fef3c7',
      badgeBorder: '#fde68a',
      badgeColor: '#92400e'
    })}`;

  return wrapHtmlDoc(bodyContent, `Payment Verification: ₹${amount} from ${customer}`);
}

export function renderPaymentReminderTemplate(data) {
  const customer = data.customerName || 'Valued Customer';
  const merchant = data.merchantName || 'Your Merchant';
  const balance = data.balance != null ? Math.abs(Number(data.balance)).toLocaleString('en-IN') : '0';
  const dueDate = data.dueDate || '';
  const actionUrl = data.actionUrl || APP_HOME_URL;

  const bodyContent = `
    ${renderHeader('Payment Settlement Reminder')}
    <tr>
      <td style="padding: 28px 24px;">
        <div style="font-size: 16px; font-weight: 700; color: #0f172a; margin-bottom: 8px;">
          Hello ${customer},
        </div>
        
        <p style="font-size: 14px; color: #334155; line-height: 1.6; margin: 0 0 20px 0;">
          This is a friendly reminder regarding your outstanding balance with <strong>${merchant}</strong>. Please find the statement summary below:
        </p>

        
        <table width="100%" border="0" cellpadding="0" cellspacing="0" style="background-color: #fff1f2; border: 1px solid #ffe4e6; border-radius: 12px; margin-bottom: 22px;">
          <tr>
            <td align="center" style="padding: 22px 16px;">
              <div style="font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.6px; color: #e11d48; margin-bottom: 4px;">
                OUTSTANDING BALANCE DUE
              </div>
              <div style="font-size: 34px; font-weight: 900; color: #e11d48; margin: 0; letter-spacing: -1px; line-height: 1.2;">
                &#8377;${balance}
              </div>
              ${dueDate ? `
              <div style="margin-top: 8px; font-size: 12px; color: #9f1239; font-weight: 600;">
                Due Date: ${dueDate}
              </div>` : ''}
            </td>
          </tr>
        </table>

        
        <table width="100%" border="0" cellpadding="0" cellspacing="0" style="margin-bottom: 20px; font-size: 13px;">
          <tr>
            <td style="padding: 10px 0; border-bottom: 1px solid #f1f5f9; color: #64748b; font-weight: 600;">Payee / Merchant:</td>
            <td align="right" style="padding: 10px 0; border-bottom: 1px solid #f1f5f9; color: #0f172a; font-weight: 700;">${merchant}</td>
          </tr>
          ${data.merchantPhone ? `
          <tr>
            <td style="padding: 10px 0; border-bottom: 1px solid #f1f5f9; color: #64748b; font-weight: 600;">Merchant Contact:</td>
            <td align="right" style="padding: 10px 0; border-bottom: 1px solid #f1f5f9; color: #0f172a; font-weight: 700;">${data.merchantPhone}</td>
          </tr>` : ''}
        </table>

        
        <table width="100%" border="0" cellpadding="0" cellspacing="0" style="margin: 28px 0 12px 0;">
          <tr>
            <td align="center">
              <a href="${actionUrl}" target="_blank" style="display: inline-block; background-color: #0057BB; background: linear-gradient(135deg, #0057BB 0%, #00479e 100%); color: #ffffff !important; text-decoration: none; padding: 14px 34px; border-radius: 12px; font-size: 14px; font-weight: 700; letter-spacing: 0.3px; box-shadow: 0 4px 14px rgba(0, 87, 187, 0.3);">
                Pay Now / View Statement &rarr;
              </a>
              <div style="font-size: 11px; color: #94a3b8; margin-top: 8px;">
                Click to pay via UPI QR or view itemized transaction bills
              </div>
            </td>
          </tr>
        </table>
      </td>
    </tr>
    ${renderFooter({
      badgeText: 'PAYMENT ADVISORY',
      badgeBg: '#fff1f2',
      badgeBorder: '#fecdd3',
      badgeColor: '#be123c'
    })}`;

  return wrapHtmlDoc(bodyContent, `Payment Reminder: ₹${balance} due to ${merchant}`);
}

export function renderTestTemplate(data) {
  const recipient = data.recipient || data.to || 'Administrator';
  const timestamp = new Date().toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' });

  const bodyContent = `
    ${renderHeader('SMTP Diagnostic Test')}
    <tr>
      <td style="padding: 30px 24px; text-align: center;">
        <div style="font-size: 40px; margin-bottom: 12px;">✅</div>
        <div style="font-size: 20px; font-weight: 800; color: #0f172a; margin-bottom: 6px;">
          SMTP Connection Successful!
        </div>
        <p style="font-size: 14px; color: #475569; line-height: 1.6; margin: 0 0 24px 0;">
          Your project email delivery gateway is online, verified, and operational.
        </p>

        
        <table width="100%" border="0" cellpadding="0" cellspacing="0" style="background-color: #f8fafc; border: 1px solid #e2e8f0; border-radius: 12px; margin-bottom: 24px;">
          <tr>
            <td style="padding: 16px 20px; text-align: left;">
              <table width="100%" border="0" cellpadding="0" cellspacing="0" style="font-size: 12px; font-family: monospace;">
                <tr>
                  <td style="padding: 4px 0; color: #64748b;">Recipient:</td>
                  <td align="right" style="padding: 4px 0; color: #0f172a; font-weight: 700;">${recipient}</td>
                </tr>
                <tr>
                  <td style="padding: 4px 0; color: #64748b;">Status:</td>
                  <td align="right" style="padding: 4px 0; color: #16a34a; font-weight: 700;">200 OK &bull; Active</td>
                </tr>
                <tr>
                  <td style="padding: 4px 0; color: #64748b;">Server Time:</td>
                  <td align="right" style="padding: 4px 0; color: #0f172a;">${timestamp} IST</td>
                </tr>
              </table>
            </td>
          </tr>
        </table>

        
        <table width="100%" border="0" cellpadding="0" cellspacing="0">
          <tr>
            <td align="center">
              <a href="${APP_HOME_URL}" target="_blank" style="display: inline-block; background-color: #0057BB; background: linear-gradient(135deg, #0057BB 0%, #00479e 100%); color: #ffffff !important; text-decoration: none; padding: 12px 28px; border-radius: 10px; font-size: 13px; font-weight: 700;">
                Return to HisabKhata &rarr;
              </a>
            </td>
          </tr>
        </table>
      </td>
    </tr>
    ${renderFooter({
      badgeText: 'SYSTEM HEALTH PASS',
      badgeBg: '#ecfdf5',
      badgeBorder: '#a7f3d0',
      badgeColor: '#065f46',
      disclaimer: 'This is an automated system diagnostic email generated by HisabKhata backend.'
    })}`;

  return wrapHtmlDoc(bodyContent, 'HisabKhata SMTP Diagnostic Test');
}

export function renderPasswordResetTemplate(data) {
  const userName = data.userName || data.customerName || data.toName || 'User';
  const resetUrl = data.actionUrl || `${APP_HOME_URL}reset-password`;
  const expiry = data.expiry || '30 minutes';

  const bodyContent = `
    ${renderHeader('Account Security Advisory')}
    <tr>
      <td style="padding: 32px 24px;">
        <div style="text-align: center; margin-bottom: 24px;">
          <div style="display: inline-block; font-size: 38px; margin-bottom: 8px;">🔒</div>
          <div style="font-size: 22px; font-weight: 800; color: #0f172a; letter-spacing: -0.5px;">
            Password Reset Request
          </div>
          <div style="font-size: 14px; color: #64748b; margin-top: 4px;">
            Secure access restoration for your HisabKhata account
          </div>
        </div>

        <p style="font-size: 14px; color: #334155; line-height: 1.6; margin: 0 0 20px 0;">
          Hello <strong>${userName}</strong>, we received a request to reset the password for your HisabKhata account. Click the button below to choose a new, secure password:
        </p>

        
        <table width="100%" border="0" cellpadding="0" cellspacing="0" style="margin: 28px 0 20px 0;">
          <tr>
            <td align="center">
              <a href="${resetUrl}" target="_blank" style="display: inline-block; background-color: #0057BB; background: linear-gradient(135deg, #0057BB 0%, #00479e 100%); color: #ffffff !important; text-decoration: none; padding: 14px 36px; border-radius: 12px; font-size: 15px; font-weight: 700; letter-spacing: 0.3px; box-shadow: 0 4px 14px rgba(0, 87, 187, 0.3);">
                Reset Your Password &rarr;
              </a>
            </td>
          </tr>
        </table>

        
        <table width="100%" border="0" cellpadding="0" cellspacing="0" style="background-color: #f8fafc; border: 1px solid #e2e8f0; border-radius: 12px; margin-bottom: 22px;">
          <tr>
            <td style="padding: 16px 20px;">
              <table width="100%" border="0" cellpadding="0" cellspacing="0" style="font-size: 12px; color: #64748b; line-height: 1.6;">
                <tr>
                  <td style="padding-bottom: 6px;">
                    ⏳ <strong>Link Expiration:</strong> This secure link will expire in <strong>${expiry}</strong>.
                  </td>
                </tr>
                <tr>
                  <td>
                    🛡️ <strong>Didn't request this?</strong> You can safely ignore this email. Your current password will remain unchanged and your account stays protected.
                  </td>
                </tr>
              </table>
            </td>
          </tr>
        </table>

        
        <div style="font-size: 11px; color: #94a3b8; word-break: break-all; line-height: 1.5; border-top: 1px solid #f1f5f9; padding-top: 14px;">
          If the button above does not work, copy and paste this link into your browser:<br/>
          <a href="${resetUrl}" target="_blank" style="color: #0057BB; text-decoration: underline;">${resetUrl}</a>
        </div>
      </td>
    </tr>
    ${renderFooter({
      badgeText: 'SECURITY VERIFICATION',
      badgeBg: '#fef2f2',
      badgeBorder: '#fecaca',
      badgeColor: '#991b1b',
      disclaimer: 'This is an official security advisory from HisabKhata. Never share your password or security tokens with anyone.'
    })}`;

  return wrapHtmlDoc(bodyContent, 'Password Reset Request - HisabKhata');
}

export function renderOtpVerificationTemplate(data) {
  const userName = data.userName || data.customerName || data.toName || 'User';
  const otpCode = String(data.otp || data.code || data.otpCode || '000000').trim();
  const purpose = data.purpose || 'account authentication';
  const expiry = data.expiry || '10 minutes';

  const bodyContent = `
    ${renderHeader('One-Time Security Code')}
    <tr>
      <td style="padding: 32px 24px; text-align: center;">
        <div style="font-size: 38px; margin-bottom: 8px;">🛡️</div>
        <div style="font-size: 22px; font-weight: 800; color: #0f172a; letter-spacing: -0.5px; margin-bottom: 4px;">
          Your Verification Code
        </div>
        <div style="font-size: 14px; color: #64748b; margin-bottom: 24px;">
          Use the OTP below to complete your ${purpose}
        </div>

        <p style="font-size: 14px; color: #334155; line-height: 1.6; margin: 0 0 24px 0; text-align: left;">
          Hello <strong>${userName}</strong>, here is your one-time verification code:
        </p>

        
        <table width="100%" border="0" cellpadding="0" cellspacing="0" style="background-color: #f0f9ff; border: 2px dashed #0057BB; border-radius: 14px; margin-bottom: 22px;">
          <tr>
            <td align="center" style="padding: 24px 16px;">
              <div style="font-size: 11px; font-weight: 800; text-transform: uppercase; letter-spacing: 1px; color: #0369a1; margin-bottom: 8px;">
                ONE-TIME PASSWORD (OTP)
              </div>
              <div style="font-size: 36px; font-weight: 900; color: #0057BB; letter-spacing: 10px; padding-left: 10px; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Courier New', Courier, monospace; line-height: 1.2; user-select: all; -webkit-user-select: all;">${otpCode}</div>
              <div style="margin-top: 10px;">
                <table border="0" cellpadding="0" cellspacing="0" align="center">
                  <tr>
                    <td bgcolor="#e0f2fe" style="background-color: #e0f2fe; color: #0284c7; font-size: 11px; font-weight: 700; padding: 4px 14px; border-radius: 9999px;">
                      ⏳ Valid for ${expiry}
                    </td>
                  </tr>
                </table>
              </div>
            </td>
          </tr>
        </table>

        
        <table width="100%" border="0" cellpadding="0" cellspacing="0" style="background-color: #fffbeb; border: 1px solid #fef3c7; border-radius: 10px; margin-bottom: 20px;">
          <tr>
            <td style="padding: 12px 16px; text-align: left; font-size: 12px; color: #92400e; line-height: 1.5;">
              ⚠️ <strong>Security Notice:</strong> Never share this OTP with anyone, including HisabKhata support or staff. We will never ask for your verification code.
            </td>
          </tr>
        </table>

        <div style="font-size: 12px; color: #94a3b8; text-align: left; line-height: 1.5;">
          If you did not initiate this verification request, please change your account password immediately to secure your ledger.
        </div>
      </td>
    </tr>
    ${renderFooter({
      badgeText: 'ONE-TIME AUTHENTICATION',
      badgeBg: '#eff6ff',
      badgeBorder: '#bfdbfe',
      badgeColor: '#1e40af',
      disclaimer: 'This is an automated authentication advisory from HisabKhata.'
    })}`;

  return wrapHtmlDoc(bodyContent, `Your HisabKhata Verification Code: ${otpCode}`);
}

export function renderWeeklyNewsletterTemplate(data) {
  const userName = data.userName || data.customerName || data.toName || 'Merchant';
  const totalCollections = data.totalCollections || data.collections != null ? Math.abs(Number(data.totalCollections || data.collections)).toLocaleString('en-IN') : '0.00';
  const activeCustomers = data.activeCustomers || data.customersCount || '0';
  const pendingSettlements = data.pendingSettlements || data.pending != null ? Math.abs(Number(data.pendingSettlements || data.pending)).toLocaleString('en-IN') : '0.00';
  const tip = data.proTip || data.tip || 'Share itemized PDF statements and UPI QR links with your customers on WhatsApp for 3x faster payment collections.';
  const actionUrl = data.actionUrl || `${APP_HOME_URL}admin`;

  const bodyContent = `
    ${renderHeader('Weekly Financial Digest')}
    <tr>
      <td style="padding: 30px 24px;">
        <div style="text-align: center; margin-bottom: 22px;">
          <div style="display: inline-block; font-size: 36px; margin-bottom: 6px;">📈</div>
          <div style="font-size: 22px; font-weight: 800; color: #0f172a; letter-spacing: -0.5px;">
            Your Weekly Ledger Snapshot
          </div>
          <div style="font-size: 13px; color: #64748b; margin-top: 4px;">
            Weekly insights, collections &amp; accounting performance
          </div>
        </div>

        <p style="font-size: 14px; color: #334155; line-height: 1.6; margin: 0 0 22px 0;">
          Hello <strong>${userName}</strong>, here is your business recap and accounting overview for the past week on HisabKhata:
        </p>

        
        <table width="100%" border="0" cellpadding="0" cellspacing="0" style="margin-bottom: 24px;">
          <tr>
            <td width="32%" bgcolor="#f0fdf4" style="background-color: #f0fdf4; border: 1px solid #dcfce7; border-radius: 12px; padding: 14px 10px; text-align: center; vertical-align: top;">
              <div style="font-size: 10px; font-weight: 800; text-transform: uppercase; color: #166534; letter-spacing: 0.5px;">
                Collected (GOT)
              </div>
              <div style="font-size: 18px; font-weight: 900; color: #16a34a; margin-top: 4px;">
                &#8377;${totalCollections}
              </div>
              <div style="font-size: 10px; color: #15803d; margin-top: 2px;">
                This Week
              </div>
            </td>
            <td width="2%">&nbsp;</td>
            <td width="32%" bgcolor="#eff6ff" style="background-color: #eff6ff; border: 1px solid #dbeafe; border-radius: 12px; padding: 14px 10px; text-align: center; vertical-align: top;">
              <div style="font-size: 10px; font-weight: 800; text-transform: uppercase; color: #1e40af; letter-spacing: 0.5px;">
                Active Ledgers
              </div>
              <div style="font-size: 18px; font-weight: 900; color: #0057BB; margin-top: 4px;">
                ${activeCustomers}
              </div>
              <div style="font-size: 10px; color: #2563eb; margin-top: 2px;">
                Customer Parties
              </div>
            </td>
            <td width="2%">&nbsp;</td>
            <td width="32%" bgcolor="#fff1f2" style="background-color: #fff1f2; border: 1px solid #ffe4e6; border-radius: 12px; padding: 14px 10px; text-align: center; vertical-align: top;">
              <div style="font-size: 10px; font-weight: 800; text-transform: uppercase; color: #9f1239; letter-spacing: 0.5px;">
                Pending Dues
              </div>
              <div style="font-size: 18px; font-weight: 900; color: #e11d48; margin-top: 4px;">
                &#8377;${pendingSettlements}
              </div>
              <div style="font-size: 10px; color: #be123c; margin-top: 2px;">
                To Collect
              </div>
            </td>
          </tr>
        </table>

        
        <table width="100%" border="0" cellpadding="0" cellspacing="0" style="background-color: #f8fafc; border-left: 4px solid #0057BB; border-radius: 0 10px 10px 0; margin-bottom: 24px;">
          <tr>
            <td style="padding: 14px 18px;">
              <div style="font-size: 12px; font-weight: 800; text-transform: uppercase; color: #0057BB; letter-spacing: 0.5px; margin-bottom: 4px;">
                💡 Pro Growth Tip for This Week
              </div>
              <div style="font-size: 13px; color: #334155; line-height: 1.5;">
                ${tip}
              </div>
            </td>
          </tr>
        </table>

        
        <table width="100%" border="0" cellpadding="0" cellspacing="0" style="background-color: #ffffff; border: 1px solid #e2e8f0; border-radius: 12px; padding: 16px; margin-bottom: 24px;">
          <tr>
            <td style="font-size: 13px; font-weight: 700; color: #0f172a; padding-bottom: 6px;">
              🚀 What's New in HisabKhata PRO:
            </td>
          </tr>
          <tr>
            <td style="font-size: 12px; color: #475569; line-height: 1.6;">
              &bull; Instant QR Online Payments with automatic UTR reference verification.<br/>
              &bull; Filter transactions by Date range, Parties, and Got/Gave categories.<br/>
              &bull; High-speed Cloudflare Worker backend for sub-second email delivery.
            </td>
          </tr>
        </table>

        
        <table width="100%" border="0" cellpadding="0" cellspacing="0" style="margin: 24px 0 12px 0;">
          <tr>
            <td align="center">
              <a href="${actionUrl}" target="_blank" style="display: inline-block; background-color: #0057BB; background: linear-gradient(135deg, #0057BB 0%, #00479e 100%); color: #ffffff !important; text-decoration: none; padding: 14px 34px; border-radius: 12px; font-size: 14px; font-weight: 700; letter-spacing: 0.3px; box-shadow: 0 4px 14px rgba(0, 87, 187, 0.3);">
                View Full Analytics in Dashboard &rarr;
              </a>
            </td>
          </tr>
        </table>
      </td>
    </tr>
    ${renderFooter({
      badgeText: 'WEEKLY FINANCIAL DIGEST',
      badgeBg: '#f8fafc',
      badgeBorder: '#e2e8f0',
      badgeColor: '#475569',
      disclaimer: 'You are receiving this weekly digest because you are a registered merchant on HisabKhata.'
    })}`;

  return wrapHtmlDoc(bodyContent, 'HisabKhata Weekly Business & Ledger Digest');
}

export function generateEmailHtml(data = {}) {
  const type = String(data.type || data.template || data.txType || '').toUpperCase();

  if (type === 'WELCOME' || type === 'ONBOARDING') {
    return renderWelcomeTemplate(data);
  }
  
  if (type === 'CUSTOMER_ADDED' || type === 'NEW_CUSTOMER') {
    return renderCustomerAddedTemplate(data);
  }

  if (type === 'PAYMENT_VERIFY' || type === 'PAYMENT_VERIFICATION' || type === 'ONLINE_PAYMENT') {
    return renderPaymentVerificationTemplate(data);
  }

  if (type === 'REMINDER' || type === 'PAYMENT_REMINDER' || type === 'DUE_ALERT') {
    return renderPaymentReminderTemplate(data);
  }

  if (type === 'PASSWORD_RESET' || type === 'RESET_PASSWORD' || type === 'FORGOT_PASSWORD') {
    return renderPasswordResetTemplate(data);
  }

  if (type === 'OTP' || type === 'OTP_VERIFICATION' || type === 'VERIFY_OTP' || type === 'AUTH_CODE' || type === 'LOGIN_OTP' || type === 'EMAIL_OTP' || type === 'SECURITY_OTP' || type === 'ALERT_OTP' || data.otp != null || data.loginOtp != null) {
    return renderOtpVerificationTemplate(data);
  }

  if (type === 'WEEKLY_NEWSLETTER' || type === 'NEWSLETTER' || type === 'WEEKLY_DIGEST' || type === 'DIGEST') {
    return renderWeeklyNewsletterTemplate(data);
  }

  if (type === 'TEST' || type === 'TEST_EMAIL') {
    return renderTestTemplate(data);
  }

  return renderTransactionTemplate(data);
}
